nodeLinker: node-modules
enableGlobalCache: true
enableImmutableInstalls: false

logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0061
    level: discard

packageExtensions:
  "baseui@*":
    peerDependencies:
      "react": "^18.2.0"
      "react-dom": "^18.2.0"
  "react-cursor-custom@*":
    peerDependencies:
      "react": "^18.2.0"
  "react-ga@*":
    peerDependencies:
      "react": "^18.2.0"
  "react-reveal@*":
    peerDependencies:
      "react": "^18.2.0"
  "react-rounded-image@*":
    peerDependencies:
      "react": "^18.2.0"
      "react-dom": "^18.2.0"
