name = "portfolio"
compatibility_date = "2024-03-25"
pages_build_output_dir = "./dist"

[build]
command = "yarn build"

[build.environment]
NODE_VERSION = "20.11.1"
YARN_VERSION = "3.2.1"
YARN_ENABLE_IMMUTABLE_INSTALLS = "false"

[site]
bucket = "./dist"

[env.production]
name = "portfolio-prod"

[env.staging]
name = "portfolio-staging" 