name = "portfolio"
compatibility_date = "2024-03-25"
pages_build_output_dir = "./dist"
main = "workers-site/index.js"

[build]
command = "yarn build"

[build.upload]
format = "service-worker"

[build.environment]
NODE_VERSION = "20.11.1"
YARN_VERSION = "3.2.1"
YARN_ENABLE_IMMUTABLE_INSTALLS = "false"

[site]
bucket = "./dist"

[env]
NODE_VERSION = "20.11.1"
YARN_VERSION = "3.2.1"
YARN_ENABLE_IMMUTABLE_INSTALLS = "false"

[env.production]
name = "portfolio-prod"

[env.preview]
name = "portfolio-preview"

[env.staging]
name = "portfolio-staging" 